#!/bin/sh
set PYTHONIOENCODING=utf8
export PYTHONIOENCODING
test -d old || mkdir old
git status -s | cut -c 4- | grep ipynb | sed 's,",,g' | while read i; do
    echo Cleaning up file "$i";
    if test -f "$i"; then
        python ./scripts/ipynb_output_filter.py < "$i" > foo.txt && \
        cp "$i" old/ && \
        mv foo.txt "$i" && \
        echo ... old copy stored in old/$i
    fi
done
